# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LalamoveSwift
  pod 'Alamofire', '~> 4.7' # For networking
  pod 'SnapKit', '~> 4.0.0' # For auto layout
  pod 'AlamofireImage' # For image downloading
  pod 'VHUD' # For showing progress
  
end
